package com.example.tmdbmovies

import org.junit.Assert.assertNotNull
import org.junit.Test

class RoomKspSmokeTest {
    @Test
    fun `Room implementation is generated by KSP`() {
        assertNotNull(Class.forName("com.example.tmdbmovies.core.database.TmdbMoviesDatabase_Impl"))
    }
}
