package com.example.tmdbmovies

import androidx.room.Database
import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.RoomDatabase
import org.junit.Assert.assertNotNull
import org.junit.Test

@Entity
internal data class KspSmokeEntity(
    @PrimaryKey val id: Long,
)

@Database(entities = [KspSmokeEntity::class], version = 1, exportSchema = false)
internal abstract class KspSmokeDatabase : RoomDatabase()

class RoomKspSmokeTest {
    @Test
    fun `Room implementation is generated by KSP`() {
        assertNotNull(Class.forName("com.example.tmdbmovies.KspSmokeDatabase_Impl"))
    }
}
